### ISSUE TITLE
Error Rendering Maps

### ISSUE THREAD

**Issue by Mooshimi** [SpaceManiac/SpacemanDMM#288]
![image](https://user-images.githubusercontent.com/85910816/134783637-30f3c800-2721-494e-bdea-c6404bbd426a.png)

Octokit.ApiValidationException: Invalid request.

Only 65535 characters are allowed; 89722 were supplied.
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 691
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 668
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 652
   at Octokit.ApiConnection.Patch[T](Uri uri, Object data, String accepts)
   at MapDiffBot.Core.GitHubManager.UpdateCheckRun(Int64 repositoryId, Int64 checkRunId, CheckRunUpdate checkRunUpdate, CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.HandleResults(PullRequest pullRequest, Int64 checkRunId, Dictionary`2 diffResults, IServiceScope scope, CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest pullRequest, Int64 checkRunId, IReadOnlyList`1 changedDmms, IServiceScope scope, CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, IServiceScope scope, CancellationToken cancellationToken)
{"message":"Invalid request.\n\nOnly 65535 characters are allowed; 89722 were supplied.","documentation_url":"https://docs.github.com/rest/reference/checks#update-a-check-run"}

**Comment by SpaceManiac** [comment]
Looks like a MapDiffBot issue, please report it there: https://github.com/tgstation/MapDiffBot/issues
