### ISSUE TITLE
Language server panic on non-ascii characters

### ISSUE THREAD

**Issue by SpaceManiac** [SpaceManiac/SpacemanDMM#39]
```
dm-langserver 0.0.1  Copyright (C) 2017-2018  Tad Hardesty
This program comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under the conditions of the GNU
General Public License version 3.

executable: D:\projects\vscode\langserver-deploy\local.exe
commit: fae911a7085470f188e62250870975133caed855
build date: 2018-09-15UTC
directory: d:\projects\tgstation-upstream
workspace root: d:\projects\tgstation-upstream
environment: d:\projects\tgstation-upstream\tgstation.dme
parsed in 4.846s
Notify NYI: workspace/didChangeConfiguration => Object({"settings": Object({"dreammaker": Object({"autoUpdate": Bool(true), "byondPath": String("c:\\Downloads\\Games\\byond"), "langserverPath": String("D:/projects/vscode/langserver-deploy/local.exe"), "maxProblems": Number(100), "tickOnCreate": Bool(true)})})})
"MAP_REMOVE" -> Some(Anything("map_remove"))
    1 results in 0.016s
"multitool_act" -> Some(Anything("multitool_act"))
    1 results in 0.016s
"power" -> Some(Anything("power"))
    140 results in 0.017s
"copytext" -> Some(Anything("copytext"))
    2 results in 0.028s
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', liballoc\string.rs:1555:30
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
   8: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:52
   9: alloc::string::String::replace_range<core::ops::range::Range<usize>>
             at \<panic macros>:3
  10: dm_langserver::document::DocumentStore::change
             at D:\projects\SpacemanDMM\src\langserver\document.rs:71
  11: dm_langserver::Engine<dm_langserver::io::StdIo, dm_langserver::io::StdIo>::handle_call<dm_langserver::io::StdIo,dm_langserver::io::StdIo>
             at D:\projects\SpacemanDMM\src\langserver\main.rs:438
  12: dm_langserver::Engine<dm_langserver::io::StdIo, dm_langserver::io::StdIo>::run<dm_langserver::io::StdIo,dm_langserver::io::StdIo>
             at D:\projects\SpacemanDMM\src\langserver\main.rs:403
  13: dm_langserver::main
             at D:\projects\SpacemanDMM\src\langserver\main.rs:61
  14: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  15: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  17: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  18: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  19: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  20: BaseThreadInitThunk
  21: RtlUserThreadStart
[Info  - 9:52:46 PM] Connection to server got closed. Server will restart.
```

**Comment by SijyKijy** [comment]
Fix it, pls!
