### ISSUE TITLE
Maps from hippiestation don't produce output or errors

### ISSUE THREAD

**Issue by Cyberboss** [SpaceManiac/SpacemanDMM#5]
E.g. boxstation at commit https://github.com/HippieStation/HippieStation/commit/ce34d0e8934f3dab4e9719e0fcecc4e8a6cd84b0

Remember to set the .dme to hippiestation.dme

Sample:

```
MapDiffBot.Generator.GeneratorException: Unable to find .png file in dmm-tools output!
parsing hippiestation.dme
Command line: -e "hippiestation.dme" minimap --disable hide-space "S:\Website\Cyberbot\App_Data\Requests\MapDiffs\Repositories\HippieStation\HippieStation\_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm.old_map_diff_bot"
parsing hippiestation.dme
Output:

parsing hippiestation.dme

Error:


   at MapDiffBot.Generator.DiffGenerator.<RenderMap>d__9.MoveNext() in S:\Documents\Actual Documents\DA Git\MapDiffBot\MapDiffBot.Generator\DiffGenerator.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.WebHook.PullRequestPayloadHandler.<GenerateMapDiff>d__13.MoveNext() in S:\Documents\Actual Documents\DA Git\MapDiffBot\MapDiffBot.Webhook\PullRequestPayloadHandler.cs:line 304
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at MapDiffBot.WebHook.PullRequestPayloadHandler.<GenerateMapDiff>d__13.MoveNext() in S:\Documents\Actual Documents\DA Git\MapDiffBot\MapDiffBot.Webhook\PullRequestPayloadHandler.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.WebHook.PullRequestPayloadHandler.<Run>d__14.MoveNext() in S:\Documents\Actual Documents\DA Git\MapDiffBot\MapDiffBot.Webhook\PullRequestPayloadHandler.cs:line 389
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.WebHook.PayloadDelegator.<>c__DisplayClass5_0.<<ProcessPayload>b__0>d.MoveNext() in S:\Documents\Actual Documents\DA Git\MapDiffBot\MapDiffBot.Webhook\PayloadDelegator.cs:line 108
```

**Comment by Cyberboss** [comment]
Duplicate of #2
